### ISSUE TITLE
Unanalyzed Code Report are not coming as attachment

### ISSUE THREAD

**Issue by nayancast** [CAST-Extend/com.castsoftware.uc.checkanalysiscompleteness#4]
I have tried to use Unanalyzed Code Report with CAST AIP 8.2.6 and 8.3.0.
Even though report gets generated but I never receive it in the mail.
I have completed the mail configuration and receives mail for other events like snapshot completion or failure.
Report generated
![image](https://user-images.githubusercontent.com/29354974/33601921-c3ec24b2-d9d3-11e7-9d4a-32c8890c00af.png)

CAST CMS Preferences
![image](https://user-images.githubusercontent.com/29354974/33601988-f72da8f0-d9d3-11e7-8f7f-78c1aeb09a13.png)

Mail settings 
![image](https://user-images.githubusercontent.com/29354974/33601956-e18bc5fe-d9d3-11e7-9ebe-9bf276668be2.png)

**Comment by MathieuRoger** [comment]
You are using a too old version where the feature was not available : please upgrade.
